name = "wordle-hint-today"

compatibility_date = "2026-09-16"

pages_build_output_dir = "dist"

compatibility_flags = [
  "nodejs_compat"
]

[[kv_namespaces]]
binding = "WORDLE_CACHE"
id = "1074e27dcebd4b6cb2b72a47888d01ad"